-- ============================================================================
-- USERS
-- ============================================================================
CREATE TABLE users (
    id              BIGSERIAL PRIMARY KEY,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(72)  NOT NULL,            -- bcrypt
    display_name    VARCHAR(100),
    role            VARCHAR(20)  NOT NULL DEFAULT 'USER',
    enabled         BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    CONSTRAINT users_role_chk CHECK (role IN ('USER', 'ADMIN'))
);

CREATE INDEX idx_users_email ON users(LOWER(email));

-- ============================================================================
-- URLS
-- ============================================================================
CREATE TABLE urls (
    id              BIGSERIAL    PRIMARY KEY,
    short_code      VARCHAR(10),                       -- nullable until populated
    long_url        TEXT         NOT NULL,
    user_id         BIGINT       REFERENCES users(id) ON DELETE CASCADE,
    title           VARCHAR(255),                      -- optional, fetched from <title>
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at      TIMESTAMPTZ,
    expires_at      TIMESTAMPTZ,                       -- v2: link expiration
    created_by_ip   INET,
    CONSTRAINT urls_short_code_unique UNIQUE (short_code),
    CONSTRAINT urls_long_url_length CHECK (LENGTH(long_url) <= 2048)
);

-- Critical index for redirect lookup (most-used query in the system)
CREATE INDEX idx_urls_short_code_active
    ON urls(short_code)
    WHERE deleted_at IS NULL AND short_code IS NOT NULL;

-- For the user dashboard (list "my URLs")
CREATE INDEX idx_urls_user_id_created_at
    ON urls(user_id, created_at DESC)
    WHERE deleted_at IS NULL;

-- ============================================================================
-- CLICK EVENTS (partitioned by month)
-- ============================================================================
CREATE TABLE click_events (
    id              BIGSERIAL,
    url_id          BIGINT       NOT NULL,
    clicked_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    referrer        VARCHAR(2048),
    user_agent      VARCHAR(512),
    ip_address      INET,
    country_code    CHAR(2),                           -- populated by geo-ip
    PRIMARY KEY (id, clicked_at)                       -- partitioning key included
) PARTITION BY RANGE (clicked_at);

-- Create initial partitions (script will create future ones automatically)
CREATE TABLE click_events_2025_01 PARTITION OF click_events
    FOR VALUES FROM ('2025-01-01') TO ('2025-02-01');
CREATE TABLE click_events_2025_02 PARTITION OF click_events
    FOR VALUES FROM ('2025-02-01') TO ('2025-03-01');
-- ... etc, generated by a scheduled job

CREATE INDEX idx_click_events_url_id_clicked_at
    ON click_events(url_id, clicked_at DESC);

-- ============================================================================
-- URL STATS (denormalized aggregate)
-- ============================================================================
CREATE TABLE url_stats (
    url_id              BIGINT       PRIMARY KEY REFERENCES urls(id) ON DELETE CASCADE,
    click_count         BIGINT       NOT NULL DEFAULT 0,
    last_clicked_at     TIMESTAMPTZ,
    -- Watermark: the latest click_event.id that has been aggregated.
    -- Aggregator queries: WHERE id > last_aggregated_event_id
    last_aggregated_event_id BIGINT NOT NULL DEFAULT 0,
    updated_at          TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- ============================================================================
-- BLOCKED DOMAINS (anti-spam)
-- ============================================================================
CREATE TABLE blocked_domains (
    domain          VARCHAR(255) PRIMARY KEY,
    reason          VARCHAR(255),
    blocked_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Seed with common spam domains in a separate migration
